name: ReitzMMO
version: "1.22"
author: Paully104
main: io.github.paulanthonyreitz.reitzmmo.Main
api-version: "1.15"
softdepend: [PlaceholderAPI]
permissions:
  reitzmmo.use:
    description: Allows use of ReitzMMO commands.
    default: true
  reitzmmo.party.use:
    description: Allows use of ReitzMMO party commands.
    default: true
  reitzmmo.reload:
    description: Allows reload of ReitzMMO
    default: op

commands:
  reitz:
    description: Main ReitzRPGMMO command listings
    usage: /reitz
    permission: reitzmmo.use
    permission-message: Sorry! You are missing the reitzmmo.use permission.
  reitz.reload:
    description: Reload ReitzMMO
    usage: /reitz reload
    permission: reitzmmo.reload
    permission-message: Sorry! You are missing the reitzmmo.use permission.
  rrm:
    description: Main ReitzRPGMMO command listings
    usage: /rrm
    permission: reitzmmo.use
    permission-message: Sorry! You are missing the reitzmmo.use permission.
  rparty:
    description: Party system for ReitzRPGMMO
    usage: /rparty
    permission: reitzmmo.party.use
    permission-message: Sorry! You are missing the reitzmmo.party.use permission.


